stages:
  test
  deploy

test_job:
  stage: test
  image: python:3.10
  script:
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    flake8 my_package
    pytest --cov=my_package --cov-report=xml
  artifacts:
    paths:
      coverage.xml
    expire_in: 1 week

deploy_job:
  stage: deploy
  image: python:3.10
  script:
    echo "Deploying artifact to staging..."
    python setup.py sdist bdist_wheel
    mkdir staging
    cp dist/*.whl staging/
  artifacts:
    paths:
      staging/*.whl
    expire_in: 1 week
  only:
    main