name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3

      - name: Set up Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest pytest-cov

      - name: Lint with Flake8
        run: flake8 my_package

      - name: Test with Pytest
        run: pytest --cov=my_package --cov-report=xml

      - name: Upload coverage
        uses: codecov/codecov-action@v3.1.4
        with:
          files: ./coverage.xml

      - name: Upload artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: staging-files
          path: staging/
